version: '2'

services:
  base-workspace:
    build:
      context: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /host/data:/var/consul                # volume for data
    environment:
      - CONSUL_VERSION=0.8.3
      - CONSULUI_VERSION=0.8.3
      - CONSULTEMPLATE_VERSION=0.18.3
      - RUBY_VERSION=2.4.1
